FROM condaforge/miniforge3

WORKDIR /app/
COPY ./docker/*.py /app/
COPY ./data /app/data/
COPY ./shell/ /app/shell/
COPY ./environment.yml /app/

RUN bash /app/shell/conda_env.sh

CMD ["bash", "/app/shell/run.sh"]